version: 1.0.{build}
image: 
  - Visual Studio 2017
install:
- cmd: git submodule update --init --recursive
before_build:
- cmd: >-
    md build;
    cd build;
    cmake -G "Visual Studio 15" ..
build:
  project: build/ALL_BUILD.vcxproj
  verbosity: minimal