version: 1.0.{build}
image: 
  - Visual Studio 2017
install:
- cmd: git submodule update --init --recursive
before_build:
- cmd: >-
    cmake -B build
build:
  project: build/ALL_BUILD.vcxproj
  verbosity: minimal