version: 1.0.{build}
image: 
  - Visual Studio 2017
  - Visual Studio 2019
  - Ubuntu1804
  - Ubuntu2004
  - macos-mojave
  - macos
install:
- cmd: git submodule update --init --recursive
before_build:
- cmd: >-
    cmake -B build
build_script: >-
  cmake --build build
  cd build
  ctest